version: "3"

volumes:
  db-data:
    external: false
  gems:
    external: false

services:
  db:
    image: mysql:5.6
    env_file: .env
    volumes:
      - db-data:/var/lib/postgresql/db-data
    ports:
      - 3308:3306

  app:
    build: ./
    env_file: .env
    volumes:
      - gems:/gems
      - .:/usr/src/app
    ports:
      - 4040:4040
    depends_on:
      - db
